/**
 * Export both transfer and unshield VKs into a single Rust file for vk.rs
 */
const fs = require("fs");

const transferVk = JSON.parse(fs.readFileSync("setup/transfer/verification_key.json", "utf8"));
const unshieldVk = JSON.parse(fs.readFileSync("setup/unshield/verification_key.json", "utf8"));

function toBE32(decStr) {
    let hex = BigInt(decStr).toString(16).padStart(64, "0");
    const bytes = [];
    for (let i = 0; i < 64; i += 2) bytes.push(parseInt(hex.substring(i, i + 2), 16));
    return bytes;
}

function formatBytes(bytes, indent = "    ") {
    const lines = [];
    for (let i = 0; i < bytes.length; i += 8) {
        const chunk = bytes.slice(i, i + 8);
        lines.push(indent + chunk.map(b => "0x" + b.toString(16).padStart(2, "0")).join(", ") + ",");
    }
    return lines.join("\n");
}

function g1Bytes(point) { return [...toBE32(point[0]), ...toBE32(point[1])]; }
function g2Bytes(point) {
    return [...toBE32(point[0][1]), ...toBE32(point[0][0]), ...toBE32(point[1][1]), ...toBE32(point[1][0])];
}

function emitVk(name, vk) {
    const alpha = g1Bytes(vk.vk_alpha_1);
    const beta = g2Bytes(vk.vk_beta_2);
    const gamma = g2Bytes(vk.vk_gamma_2);
    const delta = g2Bytes(vk.vk_delta_2);
    const ic = vk.IC.map(p => g1Bytes(p));

    let s = `/// VK for the ${name} circuit (${vk.nPublic} public inputs).\n`;
    s += `pub fn get_${name}_vk() -> VerifyingKey {\n`;
    s += `    VerifyingKey {\n`;
    s += `        alpha_g1: [\n${formatBytes(alpha)}\n        ],\n`;
    s += `        beta_g2: [\n${formatBytes(beta)}\n        ],\n`;
    s += `        gamma_g2: [\n${formatBytes(gamma)}\n        ],\n`;
    s += `        delta_g2: [\n${formatBytes(delta)}\n        ],\n`;
    s += `        ic: vec![\n`;
    for (const pt of ic) {
        s += `            [\n${formatBytes(pt, "                ")}\n            ],\n`;
    }
    s += `        ],\n    }\n}\n`;
    return s;
}

let rust = `/// Auto-generated verification keys — do not edit manually.\n`;
rust += `/// Generated by: node export_vk_pair.js\n\n`;
rust += `use crate::groth16::VerifyingKey;\n\n`;
rust += emitVk("transfer", transferVk);
rust += `\n`;
rust += emitVk("unshield", unshieldVk);

fs.writeFileSync("../programs/milk/src/vk.rs", rust);
console.log("Written to programs/milk/src/vk.rs");
console.log(`  transfer: ${transferVk.nPublic} public inputs, ${transferVk.IC.length} IC points`);
console.log(`  unshield: ${unshieldVk.nPublic} public inputs, ${unshieldVk.IC.length} IC points`);
