/**
 * Export verification_key.json to Rust byte arrays for groth16.rs
 *
 * alt_bn128 syscall format:
 *   G1 point: 64 bytes = x (32 BE) || y (32 BE)
 *   G2 point: 128 bytes = x_im (32 BE) || x_re (32 BE) || y_im (32 BE) || y_re (32 BE)
 *
 * snarkjs G2 format: [[x_re, x_im], [y_re, y_im], [z_re, z_im]]
 * Solana G2 format:   x_im || x_re || y_im || y_re  (each 32 bytes BE)
 */

const fs = require("fs");
const vk = JSON.parse(fs.readFileSync("setup/verification_key.json", "utf8"));

function toBE32(decStr) {
    let hex = BigInt(decStr).toString(16).padStart(64, "0");
    const bytes = [];
    for (let i = 0; i < 64; i += 2) {
        bytes.push(parseInt(hex.substring(i, i + 2), 16));
    }
    return bytes;
}

function formatBytes(bytes, indent = "    ") {
    const lines = [];
    for (let i = 0; i < bytes.length; i += 8) {
        const chunk = bytes.slice(i, i + 8);
        lines.push(indent + chunk.map(b => "0x" + b.toString(16).padStart(2, "0")).join(", ") + ",");
    }
    return lines.join("\n");
}

// G1 point: [x, y, z] -> 64 bytes (x || y), assuming z=1 (affine)
function g1Bytes(point) {
    return [...toBE32(point[0]), ...toBE32(point[1])];
}

// G2 point: [[x_re, x_im], [y_re, y_im], [z_re, z_im]] -> 128 bytes
// Solana format: x_im || x_re || y_im || y_re
function g2Bytes(point) {
    const x_re = toBE32(point[0][0]);
    const x_im = toBE32(point[0][1]);
    const y_re = toBE32(point[1][0]);
    const y_im = toBE32(point[1][1]);
    return [...x_im, ...x_re, ...y_im, ...y_re];
}

const alpha = g1Bytes(vk.vk_alpha_1);
const beta = g2Bytes(vk.vk_beta_2);
const gamma = g2Bytes(vk.vk_gamma_2);
const delta = g2Bytes(vk.vk_delta_2);
const ic = vk.IC.map(p => g1Bytes(p));

let rust = `/// Auto-generated from verification_key.json — do not edit manually.
/// Generated by: node export_vk_rust.js

use crate::groth16::VerifyingKey;

pub fn get_verifying_key() -> VerifyingKey {
    VerifyingKey {
        alpha_g1: [
${formatBytes(alpha)}
        ],
        beta_g2: [
${formatBytes(beta)}
        ],
        gamma_g2: [
${formatBytes(gamma)}
        ],
        delta_g2: [
${formatBytes(delta)}
        ],
        ic: vec![
`;

for (let i = 0; i < ic.length; i++) {
    rust += `            [\n${formatBytes(ic[i], "                ")}\n            ],\n`;
}

rust += `        ],
    }
}
`;

fs.writeFileSync("setup/vk_const.rs", rust);
console.log("Written to setup/vk_const.rs");
console.log(`  alpha_g1: ${alpha.length} bytes`);
console.log(`  beta_g2:  ${beta.length} bytes`);
console.log(`  gamma_g2: ${gamma.length} bytes`);
console.log(`  delta_g2: ${delta.length} bytes`);
console.log(`  IC points: ${ic.length} (${ic.length - 1} public inputs)`);
